--------------------------------------------------------
--  File created - Saturday-September-09-2023   
--------------------------------------------------------
REM INSERTING into ELECTION
SET DEFINE OFF;
Insert into ELECTION (ELECTIONCODE,DATEOFELECTION,TYPEOFELECTION,DECLARATIONDATE,LASTVOTERREGISTRATIONDATE,LASTCANDIDATURESUBMISSIONDATE,RESULTSDECLARATIONDATE) values (1,to_date('21/MAY/22','DD/MON/RR'),null,null,null,null,null);
Insert into ELECTION (ELECTIONCODE,DATEOFELECTION,TYPEOFELECTION,DECLARATIONDATE,LASTVOTERREGISTRATIONDATE,LASTCANDIDATURESUBMISSIONDATE,RESULTSDECLARATIONDATE) values (2,to_date('18/MAY/19','DD/MON/RR'),null,null,null,null,null);
Insert into ELECTION (ELECTIONCODE,DATEOFELECTION,TYPEOFELECTION,DECLARATIONDATE,LASTVOTERREGISTRATIONDATE,LASTCANDIDATURESUBMISSIONDATE,RESULTSDECLARATIONDATE) values (3,to_date('07/SEP/13','DD/MON/RR'),null,null,null,null,null);
Insert into ELECTION (ELECTIONCODE,DATEOFELECTION,TYPEOFELECTION,DECLARATIONDATE,LASTVOTERREGISTRATIONDATE,LASTCANDIDATURESUBMISSIONDATE,RESULTSDECLARATIONDATE) values (4,to_date('21/AUG/10','DD/MON/RR'),null,null,null,null,null);
Insert into ELECTION (ELECTIONCODE,DATEOFELECTION,TYPEOFELECTION,DECLARATIONDATE,LASTVOTERREGISTRATIONDATE,LASTCANDIDATURESUBMISSIONDATE,RESULTSDECLARATIONDATE) values (5,to_date('24/NOV/07','DD/MON/RR'),null,null,null,null,null);
Insert into ELECTION (ELECTIONCODE,DATEOFELECTION,TYPEOFELECTION,DECLARATIONDATE,LASTVOTERREGISTRATIONDATE,LASTCANDIDATURESUBMISSIONDATE,RESULTSDECLARATIONDATE) values (6,to_date('09/OCT/04','DD/MON/RR'),null,null,null,null,null);
