--------------------------------------------------------
--  File created - Saturday-September-09-2023   
--------------------------------------------------------
REM INSERTING into CANDIDATE
SET DEFINE OFF;
Insert into CANDIDATE (CANDID,CANDIDATENAME,CONTACTDETAILNAME,CONTACTDETAILDAYTIMEPHONE,CONTACTDETAILMOBILEPHONE,CONTACTDETAILEMAIL,PARTY_PARTYCODE) values (13321,'Darcee Stapele','Roxine Manis',null,'1187348691','rmanis0@illinois.edu','AAFI');
Insert into CANDIDATE (CANDID,CANDIDATENAME,CONTACTDETAILNAME,CONTACTDETAILDAYTIMEPHONE,CONTACTDETAILMOBILEPHONE,CONTACTDETAILEMAIL,PARTY_PARTYCODE) values (17846,'Dusty Greenstreet','Lynea Rushby',null,'1662302115','lrushby1@amazon.co.jp','AAP');
Insert into CANDIDATE (CANDID,CANDIDATENAME,CONTACTDETAILNAME,CONTACTDETAILDAYTIMEPHONE,CONTACTDETAILMOBILEPHONE,CONTACTDETAILEMAIL,PARTY_PARTYCODE) values (17258,'Gar Allatt','Lurline McGovern',null,'2697060587','lmcgovern2@soup.io','AAHP');
Insert into CANDIDATE (CANDID,CANDIDATENAME,CONTACTDETAILNAME,CONTACTDETAILDAYTIMEPHONE,CONTACTDETAILMOBILEPHONE,CONTACTDETAILEMAIL,PARTY_PARTYCODE) values (20645,'Kiley Geibel','Janella De Gregoli',null,'4863084831','jde3@rakuten.co.jp','AAPP');
Insert into CANDIDATE (CANDID,CANDIDATENAME,CONTACTDETAILNAME,CONTACTDETAILDAYTIMEPHONE,CONTACTDETAILMOBILEPHONE,CONTACTDETAILEMAIL,PARTY_PARTYCODE) values (10268,'Carlin Reinbeck','Porter Ogilvy',null,'4852036589','pogilvy4@edublogs.org','ABF');
Insert into CANDIDATE (CANDID,CANDIDATENAME,CONTACTDETAILNAME,CONTACTDETAILDAYTIMEPHONE,CONTACTDETAILMOBILEPHONE,CONTACTDETAILEMAIL,PARTY_PARTYCODE) values (20553,'Ailene McAughtrie','Saul Goare',null,'1676314995','sgoare5@fotki.com','ABR');
