--------------------------------------------------------
--  File created - Saturday-September-09-2023   
--------------------------------------------------------
REM INSERTING into ELECTIONEVENT
SET DEFINE OFF;
Insert into ELECTIONEVENT (ELECTIONEVENTID,CAMPAIGNSTARTDATE,CAMPAIGNENDDATE,NUMBEROFCANDIDATES,ELECTION_ELECTIONCODE,ELECTORATE_ELECTORATENAME,REGISTEREDVOTERSFOREVENT) values (20220521,null,null,null,1,'Adelaide',null);
Insert into ELECTIONEVENT (ELECTIONEVENTID,CAMPAIGNSTARTDATE,CAMPAIGNENDDATE,NUMBEROFCANDIDATES,ELECTION_ELECTIONCODE,ELECTORATE_ELECTORATENAME,REGISTEREDVOTERSFOREVENT) values (20190518,null,null,null,2,'Aston',null);
Insert into ELECTIONEVENT (ELECTIONEVENTID,CAMPAIGNSTARTDATE,CAMPAIGNENDDATE,NUMBEROFCANDIDATES,ELECTION_ELECTIONCODE,ELECTORATE_ELECTORATENAME,REGISTEREDVOTERSFOREVENT) values (20130907,null,null,null,3,'Ballarat',null);
Insert into ELECTIONEVENT (ELECTIONEVENTID,CAMPAIGNSTARTDATE,CAMPAIGNENDDATE,NUMBEROFCANDIDATES,ELECTION_ELECTIONCODE,ELECTORATE_ELECTORATENAME,REGISTEREDVOTERSFOREVENT) values (20100821,null,null,null,4,'Banks',null);
Insert into ELECTIONEVENT (ELECTIONEVENTID,CAMPAIGNSTARTDATE,CAMPAIGNENDDATE,NUMBEROFCANDIDATES,ELECTION_ELECTIONCODE,ELECTORATE_ELECTORATENAME,REGISTEREDVOTERSFOREVENT) values (20071124,null,null,null,5,'Barker',null);
Insert into ELECTIONEVENT (ELECTIONEVENTID,CAMPAIGNSTARTDATE,CAMPAIGNENDDATE,NUMBEROFCANDIDATES,ELECTION_ELECTIONCODE,ELECTORATE_ELECTORATENAME,REGISTEREDVOTERSFOREVENT) values (20041009,null,null,null,6,'Barton',null);
